# Generated by Django 2.2.6 on 2019-10-27 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('father', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('sputum_afb_result', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('U', 'Unknown')], max_length=1)),
                ('gxpert_result', models.CharField(choices=[('N', 'MTB not detected'), ('I', 'Invalid'), ('T', 'MTB detected'), ('RR', 'Rif resistant'), ('TI', 'MTB detected & RR is invalid or no result')], max_length=2)),
                ('cxr_result', models.CharField(choices=[('S', 'Suggestive of TB'), ('N', 'Not suggestive of TB'), ('D', 'Not Done')], max_length=1)),
                ('other_investigation', models.CharField(blank=True, max_length=100, null=True)),
                ('site_of_tb', models.CharField(choices=[('P', 'Pulmonary TB'), ('E', 'Extra Pulmonary TB')], max_length=1)),
                ('type_of_patient', models.CharField(choices=[('N', 'New'), ('P', 'Previously Treated'), ('O', 'Other'), ('M', 'MDR-TB')], max_length=1)),
                ('treatment_regimen', models.CharField(choices=[('I', 'Initial'), ('R', 'Retreatment'), ('C', 'Childhood'), ('O', 'Other')], default='I', max_length=1)),
                ('diabetes_mellitus', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('U', 'Unknown')], max_length=1)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
